[package]
name = "rs-raytracer"
version = "0.1.0"
authors = ["Max Bukhalov <bukhalovmaxim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glm = "0.2.3"

[[bin]]
name = "rs-raytracer"
path = "main.rs"
